log:
  disable_sentry: true

horizon:
  url: "http://localhost:8003"

submit:
  endpoint: "http://localhost:8003"

keys:
  source: "GBA4EX43M25UPV4WIE6RRMQOFTWXZZRIPFAI5VPY6Z2ZVVXVWZ6NEOOB"
  signer: "SAMJKTZVW5UOHCDK5INYJNORF2HRKYI72M5XSZCBYAHQHR34FFR4Z6G4"

db:
  url: "postgres://blobs:blobs@localhost:5435/blobs?sslmode=disable"

listener:
  addr: :8004

cop:
  disabled: true
  endpoint: "http://..."
  upstream: "http://..."
  service_name: blobs
  service_port: 80